import type { Metadata } from "next";
import "@/styles/globals.css";
import NavigationBar from "@/components/navbar/NavigationBar";
import { ChakraProvider } from "@chakra-ui/react";
import { Provider } from "@/components/ui/provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-[#000814] font-roboto">
        <Provider>
          <NavigationBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
